# Generated by Django 4.2.27 on 2025-12-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
    ]
